services:
  bookgrab:
    build: .
    container_name: bookgrab
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "mousehole:/mousehole-state:ro"
    restart: unless-stopped

volumes:
  mousehole:
    external: true
